import { resolveRecipe } from '@nn-playground/shared';
import type { RecipeCatalogEntry } from '@nn-playground/shared';
import type { LessonDefinition, LessonTarget } from './types.ts';

export const VALID_LESSON_TARGETS = [
    'data',
    'features',
    'network',
    'hyperparams',
    'transport',
] as const satisfies readonly LessonTarget[];

export const DEFAULT_LESSON_ID = 'lesson-xor-hidden-layers';

export const LESSON_DEFINITIONS = [
    {
        id: 'lesson-xor-hidden-layers',
        title: 'XOR Needs Hidden Layers',
        summary: 'See why a straight boundary cannot solve XOR and how hidden layers create bends.',
        recipeRef: { id: 'xor-hidden', revision: 1 },
        estimatedMinutes: 4,
        steps: [
            {
                id: 'read-xor-pattern',
                title: 'Read the XOR pattern',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'The XOR preset alternates labels by quadrant, so no single straight line can separate every point.',
                tryThis: 'Check that XOR is selected, then read the samples, noise, and train/test summary.',
            },
            {
                id: 'give-model-capacity',
                title: 'Give the model capacity',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'Two hidden layers let the network combine simple bends into the corners needed for XOR.',
                tryThis: 'Count the two hidden layers, then compare their neuron widths in the Network controls.',
            },
            {
                id: 'use-steady-updates',
                title: 'Use steady updates',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'A moderate learning rate and small batches make the loss react without bouncing wildly.',
                tryThis: 'Compare the Learning rate and Batch size controls, then note the selected settings.',
            },
            {
                id: 'train-in-small-moves',
                title: 'Train in small moves',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Step or play from the transport controls and watch the boundary change as weights update.',
                tryThis: 'Select Step once, then watch the XOR decision boundary update in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-single-neuron-linear-separator',
        title: 'Single Neuron Linear Separator',
        summary: 'Start with the smallest classifier and see why one neuron draws one straight boundary.',
        recipeRef: { id: 'single-neuron', revision: 1 },
        estimatedMinutes: 3,
        steps: [
            {
                id: 'inspect-gaussian-data',
                title: 'Inspect the two clusters',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'The Gaussian dataset places two clouds where a straight separator is enough to split the labels.',
                tryThis: 'Check that Gaussian is selected, then read the samples, noise, and train/test summary.',
            },
            {
                id: 'inspect-single-neuron',
                title: 'Use one neuron',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'With no hidden layers, the model can only learn a weighted sum of the input features.',
                tryThis: 'Check that Hidden Layers shows 0, then notice the network still has one output neuron.',
            },
            {
                id: 'train-linear-boundary',
                title: 'Train the straight boundary',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Run a few steps and watch the boundary rotate toward the gap between the two clusters.',
                tryThis: 'Select Step once, then watch the straight boundary rotate between clusters in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-regression-plane-baseline',
        title: 'Regression Plane Baseline',
        summary: 'Switch from class labels to continuous values and fit a simple plane.',
        recipeRef: { id: 'regression-plane', revision: 1 },
        estimatedMinutes: 3,
        steps: [
            {
                id: 'switch-to-regression',
                title: 'Switch to regression data',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'Regression predicts a continuous surface instead of choosing between classes.',
                tryThis: 'Check that Problem shows Regression and Plane is selected in the Regression data controls.',
            },
            {
                id: 'inspect-regression-settings',
                title: 'Use regression settings',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Mean squared error and a linear output match a continuous target better than classification settings.',
                tryThis: 'Open the Loss control and check that the regression setting uses mean squared error.',
            },
            {
                id: 'confirm-linear-model',
                title: 'Keep the model linear',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'No hidden layer is needed when the target is already shaped like a plane.',
                tryThis: 'Check that Hidden Layers shows 0, then trace the linear model from inputs to output.',
            },
            {
                id: 'train-plane-fit',
                title: 'Train the plane fit',
                target: 'transport',
                phase: 'run',
                evidenceView: 'loss',
                body: 'Run training and watch the loss drop as the plane aligns with the generated surface.',
                tryThis: 'Select Step once, then watch the regression curve update in Results → Learning.',
            },
        ],
    },
    {
        id: 'lesson-circle-hidden-layer',
        title: 'Circle With One Hidden Layer',
        summary: 'Watch a small hidden layer bend a straight model into a circular boundary.',
        recipeRef: { id: 'circle-one-layer', revision: 1 },
        estimatedMinutes: 4,
        steps: [
            {
                id: 'read-circle-shape',
                title: 'Read the circle shape',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'The circle dataset puts one class near the center and the other around it, so a straight line cannot separate both rings.',
                tryThis: 'Check that Circle is selected, then compare the Samples, Train ratio, and Noise controls.',
            },
            {
                id: 'use-one-hidden-layer',
                title: 'Use one hidden layer',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'A single hidden layer gives the model several small bends that can combine into a rounded boundary.',
                tryThis: 'Count the single hidden layer, then check how many neurons it gives the network.',
            },
            {
                id: 'keep-updates-smooth',
                title: 'Keep updates smooth',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Moderate learning settings make it easier to see the boundary curve inward instead of jumping around.',
                tryThis: 'Compare the Learning rate and Batch size controls before training the circle.',
            },
            {
                id: 'train-circle-boundary',
                title: 'Train the curved boundary',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Run training and compare the center region against the outer ring as the hidden layer learns the curve.',
                tryThis: 'Select Step once, then watch for the circle boundary to change in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-feature-engineering-circle',
        title: 'Feature Engineering Helps',
        summary: 'Use squared inputs to make a circular problem easier before adding hidden layers.',
        recipeRef: { id: 'feature-engineering', revision: 1 },
        estimatedMinutes: 4,
        steps: [
            {
                id: 'inspect-engineered-features',
                title: 'Inspect engineered features',
                target: 'features',
                tab: 'features',
                phase: 'build',
                body: 'Squared coordinate features expose distance-from-center information that the raw x and y inputs hide from a linear model.',
                tryThis: 'Check that the x² and y² feature buttons are selected alongside the raw inputs.',
            },
            {
                id: 'compare-with-linear-model',
                title: 'Keep the network simple',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'With the right features, even a model with no hidden layers can draw a useful circular separator.',
                tryThis: 'Check that Hidden Layers shows 0, then notice how the engineered features keep the model linear.',
            },
            {
                id: 'use-classification-loss',
                title: 'Use classification loss',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Cross-entropy and a sigmoid output keep the lesson focused on class probability rather than regression error.',
                tryThis: 'Read the classification loss summary and check that it uses cross-entropy.',
            },
            {
                id: 'train-feature-model',
                title: 'Train the feature model',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Run training and notice how the boundary becomes round without adding hidden-layer capacity.',
                tryThis: 'Select Step once, then watch the feature-driven boundary update in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-spiral-depth',
        title: 'Spiral Needs Depth',
        summary: 'Explore why twisted data needs more capacity and steadier training.',
        recipeRef: { id: 'spiral-deep', revision: 1 },
        estimatedMinutes: 5,
        steps: [
            {
                id: 'read-spiral-twist',
                title: 'Read the spiral twist',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'The spiral arms wrap around each other, so the model needs many local bends to follow the class boundary.',
                tryThis: 'Check that Spiral is selected, then compare the Samples, Train ratio, and Noise controls.',
            },
            {
                id: 'inspect-deeper-network',
                title: 'Inspect the deeper network',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'Multiple hidden layers let early bends combine into more detailed bends later in the network.',
                tryThis: 'Count the hidden layers and compare their neuron widths in the Network controls.',
            },
            {
                id: 'slow-spiral-learning',
                title: 'Slow the learning down',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'A smaller learning rate helps the deeper model adjust gradually instead of overshooting the narrow spiral arms.',
                tryThis: 'Check the Learning rate value and notice that the spiral preset uses 0.01.',
            },
            {
                id: 'train-spiral-boundary',
                title: 'Train the spiral boundary',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Run training for longer than the simpler lessons and watch the boundary untwist section by section.',
                tryThis: 'Select Step once, then watch for a local spiral-boundary change in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-learning-rate-tuning',
        title: 'Learning Rate Tuning',
        summary: 'Compare update sizes and learn why steady progress beats dramatic jumps.',
        recipeRef: { id: 'xor-hidden', revision: 1 },
        estimatedMinutes: 4,
        steps: [
            {
                id: 'find-learning-rate-controls',
                title: 'Find the update-size controls',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Learning rate controls how far each training update moves the weights after a gradient step.',
                tryThis: 'Read the Learning rate value before changing or running anything.',
            },
            {
                id: 'connect-rate-to-loss',
                title: 'Connect rate to the loss curve',
                target: 'transport',
                phase: 'run',
                evidenceView: 'loss',
                body: 'Step through training and watch whether loss falls smoothly, stalls, or jumps around.',
                tryThis: 'Select Step once, then compare the new and previous points in Results → Learning.',
                completion: { kind: 'training-step-at-least', step: 1 },
            },
            {
                id: 'keep-capacity-fixed',
                title: 'Keep the model fixed',
                target: 'network',
                tab: 'network',
                body: 'Change one idea at a time: keep the topology stable while experimenting with update size.',
                tryThis: 'Select Setup → Network, then check that the hidden-layer topology is unchanged.',
                completion: { kind: 'setup-tab-is', tab: 'network' },
            },
            {
                id: 'retry-with-smaller-steps',
                title: 'Retry with smaller steps',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                evidenceView: 'loss',
                body: 'After changing the learning rate or clipping settings, apply changes and run again to compare the curve.',
                tryThis: 'Change Learning rate, select Apply changes, open Results → Learning, run training, then compare the new curve in Results → Learning.',
            },
        ],
    },
    {
        id: 'lesson-regularization-overfitting',
        title: 'Regularization and Overfitting',
        summary: 'Use regularization and capacity choices to manage the gap between train and test behavior.',
        recipeRef: { id: 'spiral-deep', revision: 1 },
        estimatedMinutes: 5,
        steps: [
            {
                id: 'start-with-flexible-model',
                title: 'Start with a flexible model',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'A deeper network can trace complicated data, but extra flexibility can also memorize noisy details.',
                tryThis: 'Count the hidden layers and neuron widths that make this network flexible.',
            },
            {
                id: 'open-regularization-controls',
                title: 'Open regularization controls',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Regularization nudges the model toward smaller weights so it must prefer simpler explanations.',
                tryThis: 'Open the Regularization section and check the selected Penalty.',
            },
            {
                id: 'compare-training-and-holdout',
                title: 'Compare training and holdout',
                target: 'transport',
                phase: 'run',
                evidenceView: 'loss',
                body: 'Run training and watch for a pattern where training improves faster than held-out test behavior.',
                tryThis: 'Select Play, then compare train and test loss when the next full evaluation appears in Results → Learning.',
            },
            {
                id: 'simplify-or-regularize',
                title: 'Simplify or regularize',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                evidenceView: 'loss',
                body: 'After simplifying or regularizing, run another short trial and compare whether the train/test gap narrows.',
                tryThis: 'Change Penalty, select Apply changes, open Results → Learning, run training, then compare the train/test gap in Results → Learning.',
            },
        ],
    },
    {
        id: 'lesson-noisy-data-robustness',
        title: 'Noisy Data Robustness',
        summary: 'Learn why noisy points need smoother decisions and more cautious interpretation.',
        recipeRef: { id: 'circle-one-layer', revision: 1 },
        estimatedMinutes: 4,
        steps: [
            {
                id: 'inspect-noise-controls',
                title: 'Inspect the noise controls',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'Noise moves points away from the clean pattern, so a perfect boundary may be the wrong goal.',
                tryThis: 'Move the Noise control slightly, then read the updated noise value in Setup → Dataset.',
            },
            {
                id: 'prefer-smooth-boundaries',
                title: 'Prefer smooth boundaries',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'A modest hidden layer can capture the circle while avoiding tiny bends around individual noisy points.',
                tryThis: 'Count the hidden layers and neuron widths, then check the selected Hidden activation.',
            },
            {
                id: 'use-conservative-settings',
                title: 'Use conservative settings',
                target: 'hyperparams',
                tab: 'hyperparams',
                phase: 'build',
                body: 'Regularization and steady update sizes help the model ignore isolated noisy examples.',
                tryThis: 'Check the Regularization and Learning rate settings before training on noisy data.',
            },
            {
                id: 'train-and-read-uncertainty',
                title: 'Train and read uncertainty',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Run training, then treat uncertain or isolated mistakes as signals about data quality, not just model quality.',
                tryThis: 'Select Play, then compare uncertain regions with isolated noisy points in Results → Boundary.',
            },
        ],
    },
    {
        id: 'lesson-three-class-softmax',
        title: 'Three-Class Softmax Lab',
        summary: 'Learn how three output neurons compete through softmax on a compact multiclass dataset.',
        recipeRef: { id: 'three-class-clusters', revision: 1 },
        estimatedMinutes: 5,
        steps: [
            {
                id: 'read-three-clusters',
                title: 'Read the three clusters',
                target: 'data',
                tab: 'data',
                phase: 'build',
                body: 'Each point belongs to Class 0, Class 1, or Class 2, so the model must choose among three labels instead of drawing a binary split.',
                tryThis: 'Check that Problem shows Multiclass classification and Three-Class is selected.',
            },
            {
                id: 'inspect-three-outputs',
                title: 'Inspect the three outputs',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'The network uses one output neuron per class. Softmax turns those outputs into competing confidence scores.',
                tryThis: 'Check the network summary for three output neurons, one for each class.',
            },
            {
                id: 'connect-softmax-loss',
                title: 'Keep the softmax tuple together',
                target: 'network',
                tab: 'network',
                phase: 'build',
                body: 'This preset keeps three outputs, softmax, and categorical cross-entropy paired so the highest class score wins after each update.',
                tryThis: 'Read the output and loss summaries and confirm softmax is paired with categorical cross-entropy.',
            },
            {
                id: 'train-class-regions',
                title: 'Train three class regions',
                target: 'transport',
                phase: 'run',
                evidenceView: 'boundary',
                body: 'Start training and watch the boundary divide the plane into three winning-class regions, with uncertainty near class borders.',
                tryThis: 'Select Step once, then watch the three winning-class regions update in Results → Boundary.',
            },
        ],
    },
] as const satisfies readonly LessonDefinition[];

export function getLessonDefinition(id = DEFAULT_LESSON_ID): LessonDefinition | null {
    return LESSON_DEFINITIONS.find((lesson) => lesson.id === id) ?? null;
}

export function getLessonRecipe(lesson: LessonDefinition): RecipeCatalogEntry {
    const entry = resolveRecipe(lesson.recipeRef);
    if (!entry) {
        throw new Error(
            `Missing guided lesson recipe: ${lesson.recipeRef.id}@${lesson.recipeRef.revision}`,
        );
    }
    return entry;
}

export type {
    LessonCompletionRule,
    LessonDefinition,
    LessonStep,
    LessonTarget,
} from './types.ts';
